pipeline {
  agent {
    kubernetes {
        yaml """\
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        podtype: mysql
    spec:
      serviceAccountName: jenkins-agent
      containers:
      - name: mysqlclient
        image: mysql:8.0.25
        command:
        - cat
        tty: true
    """.stripIndent()
    }
  }
  parameters {
    string(name: 'Namespace', description: 'The namespace of your environment in Kuberetes')
    string(name: 'DBUSER', description: 'The database users', default: 'root')
    password(name: 'DBPASSWORD', description: 'The database users password', default: 'secret123')
  }
  stages {
    stage('Apply SQL update') {
      steps {
        container(name: 'mysqlclient') {
          sh '''
            mysql -u${DBUSER} -p${DBPASSWORD} -h${DBHOST}.${Namespace} orderbook -e SQL/prodsafe.sql
  '''
        }
      }
    }
  }
}
